export type FaithType = {
  title: string;
  description: string;
};

export const faithDeclarations: FaithType[] = [
  {
    title: 'Scriptures',
    description:
      'We believe the Old and New Testaments, in their original writing, are fully inspired of God and are the supreme and final authority for faith and life.',
  },
  {
    title: 'One God',
    description:
      'We believe in one God, eternally existing in three Persons — Father, Son, and Holy Spirit.',
  },
  {
    title: 'Jesus Christ',
    description:
      'We believe Jesus Christ was begotten of the Father, conceived by the Holy Spirit, born of the Virgin Mary, and is true God and true man.',
  },
  {
    title: 'Humanity',
    description:
      'We believe God created man in His image; man sinned and incurred the penalty of death physically and spiritually; all inherit a sinful nature resulting in personal guilt.',
  },
  {
    title: 'Atonement',
    description:
      'We believe the Lord Jesus Christ died for our sins as a substitutionary sacrifice and all who believe are justified on the grounds of His shed blood.',
  },
  {
    title: 'Resurrection & Ascension',
    description:
      'We believe in the bodily resurrection of Jesus, His ascension into Heaven, and His present life as our High Priest and Advocate.',
  },
  {
    title: 'Second Coming',
    description: 'We believe in the personal return of the Lord Jesus Christ.',
  },
  {
    title: 'New Birth',
    description:
      'We believe all who repent and receive Jesus Christ by faith are born again of the Holy Spirit and become children of God.',
  },
  {
    title: 'Discipleship',
    description:
      'We believe the church’s responsibility is to make disciples of all nations and assimilate disciples into the local church.',
  },
  {
    title: 'Resurrection & Judgment',
    description:
      'We believe in the resurrection of both the just and the unjust; the eternal blessedness of the redeemed and the eternal banishment of those who reject salvation.',
  },
  {
    title: 'Holy Spirit',
    description:
      'We believe in the baptism in the Holy Spirit, empowering and equipping believers for service, with accompanying supernatural gifts, and in fellowship with the Holy Spirit.',
  },
  {
    title: 'Ministries',
    description:
      'We believe in the divinely ordained ministries of Apostle, Prophet, Evangelist, Pastor, and Teacher.',
  },
  {
    title: 'Authority & Governance',
    description:
      'We believe submission to authority is essential; membership is subject to submission in matters of governance, doctrine, and personal behaviour.',
  },
  {
    title: 'The Church',
    description:
      'We believe the one true Church comprises those redeemed by Christ and regenerated by the Spirit; new birth and personal confession of Christ are essentials of membership.',
  },
  {
    title: 'Ordinances',
    description:
      'We believe the Lord appointed Baptism in water and the Lord’s Supper to be observed as acts of obedience and perpetual witnesses to the cardinal facts of the Christian faith.',
  },
  {
    title: 'Divine Healing',
    description:
      'We believe divine healing was provided for in the Old and New Testaments and is an integral part of the Gospel.',
  },
  {
    title: 'Holiness & Sanctification',
    description:
      'We believe without holiness no man shall see the Lord; sanctification is definite yet progressive from new birth to the consummation of salvation.',
  },
  {
    title: 'Sexual Behaviour',
    description:
      'We believe in heterosexual relationships between a natural man and a natural woman within lawful matrimony; adherence to this principle is required for membership.',
  },
  {
    title: 'Church Discipline',
    description:
      'We believe local church leadership has authority to withdraw membership for serious, unrepentant misconduct or similar cause.',
  },
  {
    title: 'Further Truth',
    description:
      'We believe the Church must remain open to any further truth the Holy Spirit may illuminate from the Scriptures.',
  },
];
